#!/bin/sh

if test -e "$HOME"/.config/orchis/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Link Libadwaita and Change fstab"
cp -r /usr/share/themes/Orchis-Dark-Compact/gtk-4.0 ~/.config
sed -i 's/compress=zstd:1/-systemd.device-timeout=0,ssd,noatime,space_cache,commit=120,compress=zstd:1/g' /etc/fstab
echo "10"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "30"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "40"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "50"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "80"

echo "# Installing Librewolf"
/usr/bin/flatpak install --user --noninteractive flathub io.gitlab.librewolf-community
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Librewolf Failed"
        exit 1
fi
echo "85"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "90"

echo "Enabling Flatpak auto update"
/usr/bin/systemctl --user enable --now flatpak-user-update.timer
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Setting Flatpak Autoupdate Failed"
        exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/orchis/
touch "$HOME"/.config/orchis/firstboot-done
cp -n /etc/justfile "$HOME"/.justfile

) | 
     
   zenity --progress --title="Orchis Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
